#!/usr/bin/env bash
youtube-dl https://www.youtube.com/watch?v=ZnTClmRzADE
youtube-dl https://www.youtube.com/watch?v=OQneiz_9nkA
youtube-dl https://www.youtube.com/watch?v=x6cG2jeXlE8
youtube-dl https://www.youtube.com/watch?v=CV-Ffmqv4mg
youtube-dl https://www.youtube.com/watch?v=04lszrCxBYA
youtube-dl https://www.youtube.com/watch?v=Rp6D5_XZF6E
youtube-dl https://www.youtube.com/watch?v=ISkjUbwIlV4
youtube-dl https://www.youtube.com/watch?v=OS7fvPM5kHc
youtube-dl https://www.youtube.com/watch?v=0KvWPgPGTX8
youtube-dl https://www.youtube.com/watch?v=CEYNsGlbKNE
youtube-dl https://www.youtube.com/watch?v=SiF7rnumHj4
youtube-dl https://www.youtube.com/watch?v=elqEh2BAVuo
youtube-dl https://www.youtube.com/watch?v=PT2_F-1esPk
youtube-dl https://www.youtube.com/watch?v=agFMqNB9BYM
